### ISSUE TITLE
Where the frick are the memeseeks sprites located?

### ISSUE THREAD

**Issue by EXTREMETIERSHIFTAG1** [BigSlice/-tg-station#34]
Ayy, tell me where they are and I'll try to make the malfunctioning robot sprite(people are giving this idea in bread) so we can finally remove this meme out of the face of the game.

**Comment by BigSlice** [comment]
I completely deleted the sounds and code but the sprites should be in icons/mob/human.dmi,  icons/obj/food/burgerbread.dmi,  icons/obj/food/food.dmi, and  icons/obj/objects.dmi.
