### ISSUE TITLE
Stealing sprites from /tg/ overall

### ISSUE THREAD

**Issue by ihategithubbb** [BigSlice/-tg-station#42]
Are you against this BigSlice and Co?
I mean, they got some really nice sprites which we could ste-I mean borrow.
For example, look in this thread here, it has some 10/10 clothings and 10/10 gun sprites too, everything looks pretty neato.
https://tgstation13.org/phpBB/viewtopic.php?f=11&t=7&hilit=sprites
(forgive me for directly liking tg shit)

**Comment by BigSlice** [comment]
Moved to #4
