### ISSUE TITLE
[idea]Battering Ram for sec

### ISSUE THREAD

**Issue by abigfagg** [BigSlice/-tg-station#69]
/tg/ is making a battering ram for sec, an unique item that takes around 8 seconds to open any door(even bolted ones)
Now, we could change it not to open airlocks and bolted doors, put it on the armory and give it a 12 seconds time instead to make it balanced, how does that sound/
/tg/ pull: https://github.com/tgstation/-tg-station/pull/17557

**Comment by BigSlice** [comment]
Moved to #4
