### ISSUE TITLE
We need more wizard names.

### ISSUE THREAD

**Issue by abigfagg** [BigSlice/-tg-station#71]
Only 36?What the fuck, we need more useless fluff names!
Kredeleus
Adyvius
Uowix
Cruynas
Frogomonar
Phisabus
Cliyorn
Odatrix
Odwyn
Yrviar
Oqyjor
Ovrikasorin
Oharad
Xukore
Kluqoqiohr
Fofexius
Ibuharis
Purhan
Oztior
Yphith
Stabemarim
Stroxumonar
Uwix
Ucreyorn
Woqeronin
Ezimodel
Ofluras
Kneprix
Ipvius
Amneus

Also, if female wizards are a thing, remove them entirely.

**Comment by abigfagg** [comment]
Historical name pack:
Atlantes, an evil sorcerer in the Matter of France
Baba Yaga, a sorceress in Slavic mythology similar to a witch
Circe, Greek sorceress
Farmer Weathersky
Fitcher in the fairy tale Fitcher's Bird
Fioravante in the fairy tale Cannetella
Gwydion in Welsh mythology
Jannes and Jambres from Hebrew theology.
Maestro Lattantio in Maestro Lattantio and His Apprentice Dionigi
Maugris, an enchanter in the Matter of France
Medea in Greek mythology
Merlin - the famous wizard from Arthurian legends and their modern retellings.
Morgan le Fay - an enchantress in both the Matter of Britain and the Matter of France
The Telchines - four wizards of ancient Greek myths.
Väinämöinen - the grand wizard of Kalevala

**Comment by BigSlice** [comment]
Moved to #4
