### ISSUE TITLE
[idea] Let's steal delusion.

### ISSUE THREAD

**Issue by githubisforfags** [BigSlice/-tg-station#76]
/tg/ has a hallucination type called "delusion", in which you see every mob as something else, I think it's fairly interesting and we don't seem to have it.
https://github.com/tgstation/-tg-station/blob/e6d0a8108698fe870db46bb9328dc95c5bab4d42/code/modules/flufftext/Hallucination.dm
Lines 278 to 309, then 557 and 558

**Comment by BigSlice** [comment]
Moved to #4
