### ISSUE TITLE
Blood Soup recipe makes Tomato Soup

### ISSUE THREAD

**Issue by ben1488garrison** [BigSlice/-tg-station#89]
Properly consumes all materials (Blood from a container, Blood Tomato, Bowl), yet it creates Tomato Soup.

**Comment by Merege** [comment]
Seems the blood soup has the name 'tomato soup' but a different description, I'm not sure if this is intentional

**Comment by ben1488garrison** [comment]
Looks like it is.

Blood soup crafts "tomato soup".
Smells like copper.

That's a tomato soup.
Drinking this feels like being a vampire! A tomato vampire...

Actual tomato soup provides Tomato Juice and Water (on top of nutriment and vitamin) to the one consuming it.
