### ISSUE TITLE
Wizard Academy away mission balance

### ISSUE THREAD

**Issue by 0aktree** [BigSlice/-tg-station#90]
Some players complained of the Wizard Academy granting a far disproportionate amount of power for how little risk is involved in securing it.
Context is a shift where guns/magic awarding spells were used and the Avatar of Nar'Sie was released upon the station, with the result being nearly all of the crew turned into harvesters.

Merege said he didn't want to touch balance stuff like this.

**Comment by BigSlice** [comment]
I think I see the problem here. The spellbook placed there was never intended to have charges, so I removed it.
